export const UPLOAD_ART_REQUEST = 'UPLOAD_ART_REQUEST'
export const UPLOAD_ART_SUCCESS = 'UPLOAD_ART_SUCCESS'
export const UPLOAD_ART_FAIL = 'UPLOAD_ART_FAIL'
export const UPLOAD_ART_RESET = 'UPLOAD_ART_RESET'


export const GET_ALL_ARTS_REQUEST = 'GET_ALL_ARTS_REQUEST'
export const GET_ALL_ARTS_SUCCESS = 'GET_ALL_ARTS_SUCCESS'
export const GET_ALL_ARTS_FAIL = 'GET_ALL_ARTS_FAIL'


export const GET_USER_ARTS_REQUEST = 'GET_USER_ARTS_REQUEST'
export const GET_USER_ARTS_SUCCESS = 'GET_USER_ARTS_SUCCESS'
export const GET_USER_ARTS_FAIL = 'GET_USER_ARTS_FAIL'


export const DELETE_USER_ART_REQUEST = 'DELETE_USER_ART_REQUEST'
export const DELETE_USER_ART_SUCCESS = 'DELETE_USER_ART_SUCCESS'
export const DELETE_USER_ART_FAIL = 'DELETE_USER_ART_FAIL'


export const LOAD_ART_REQUEST = 'LOAD_ART_REQUEST'
export const LOAD_ART_SUCCESS = 'LOAD_ART_SUCCESS'
export const LOAD_ART_FAIL = 'LOAD_ART_FAIL'

export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST'
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS'
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL'
export const ADD_REVIEW_REST = 'ADD_REVIEW_REST'

export const GET_ART_REVIEWS_REQUEST = 'GET_ART_REVIEWS_REQUEST'
export const GET_ART_REVIEWS_SUCCESS = 'GET_ART_REVIEWS_SUCCESS'
export const GET_ART_REVIEWS_FAIL = 'GET_ART_REVIEWS_FAIL'



export const UPDATE_ART_REQUEST = 'UPDATE_ART_REQUEST'
export const UPDATE_ART_SUCCESS = 'UPDATE_ART_SUCCESS'
export const UPDATE_ART_FAIL = 'UPDATE_ART_FAIL'
export const UPDATE_ART_RESET = 'UPDATE_ART_RESET'