export const MAKE_OFFER_REQUEST = 'MAKE_OFFER_REQUEST'
export const MAKE_OFFER_SUCCESS = 'MAKE_OFFER_SUCCESS'
export const MAKE_OFFER_FAIL = 'MAKE_OFFER_FAIL'
export const RESET_MAKE_OFFER = 'RESET_MAKE_OFFER'



export const GET_OFFERS_REQUEST = 'GET_OFFERS_REQUEST'
export const GET_OFFERS_SUCCESS = 'GET_OFFERS_SUCCESS'
export const GET_OFFERS_FAIL = 'GET_OFFERS_FAIL'

export const ACCEPT_OFFER_REQUEST = 'ACCEPT_OFFER_REQUEST'
export const ACCEPT_OFFER_SUCCESS = 'ACCEPT_OFFER_SUCCESS'
export const ACCEPT_OFFER_FAIL = 'ACCEPT_OFFER_FAIL'