export const CREATE_PDF_REQUEST = 'CREATE_PDF_REQUEST'
export const CREATE_PDF_FAIL = 'CREATE_PDF_FAIL'
export const CREATE_PDF_SUCCESS = 'CREATE_PDF_SUCCESS'
export const CREATE_PDF_RESET_STATE = 'CREATE_PDF_RESET_STATE'


export const GET_ALL_PDF_REQUEST = 'GET_ALL_PDF_REQUEST'
export const GET_ALL_PDF_SUCCESS = 'GET_ALL_PDF_SUCCESS'
export const GET_ALL_PDF_FAIL = 'GET_ALL_PDF_FAIL'